# -*- coding: utf-8 -*-
"""remove trailing slash

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17cpQDBRA3aWFY-n2aLf3QSbCv_aiynXC
"""

import pandas as pd
from google.colab import files

# Function to remove the trailing slash from URLs
def remove_trailing_slash(url):
    if url.endswith('/'):
        return url[:-1]  # Remove the last character if it is a slash
    return url  # Return the original URL if no trailing slash

# Uploading the CSV file containing links
print("Please upload the CSV file containing URLs.")
uploaded = files.upload()

# Get the name of the uploaded file
file_name = list(uploaded.keys())[0]

try:
    # Reading the CSV file
    df = pd.read_csv(file_name)

    # Check if the CSV has a column named 'URLs'
    if 'URLs' in df.columns:
        # Applying the function to remove trailing slashes
        df['Cleaned URLs'] = df['URLs'].apply(remove_trailing_slash)

        # Saving the cleaned URLs to a new CSV file
        output_file = "/content/cleaned_urls.csv"
        df.to_csv(output_file, index=False)

        # Displaying the output file path
        print(f"Cleaned URLs saved to: {output_file}")
    else:
        print("Error: The CSV file must contain a column named 'URLs'.")
except Exception as e:
    print(f"An error occurred: {e}")